name: Run shell script
on: 
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter a message'  # ユーザに表示される説明文
        required: true                 # 入力が必須かどうか
        default: 'Hello, world!'       # デフォルト値

jobs:
  shell_script_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run shell script
      run: |
        chmod +x ./script.sh
        ./script.sh ${{ secrets.SAMPLE_1 }} ${{ secrets.SAMPLE_2 }} ${{ github.event.inputs.message }}